version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3456:3456"
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" 